name: muffet rot link check
on:
  push:
    branches:
      - master
jobs:
  check:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: ./scripts/muffet -c 32 -e '#!$' -e '.*github.com/geekodour/wiki/edit.*' --timeout 45 https://wiki.geekodour.xyz
