name: muffet rot link check
on:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  check:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: ./scripts/broken_link_check.sh
