name: muffet rot link check
on:
  push:
    branches:
      - master
jobs:
  check:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: make rot-link-check

